name: GitHub-Profile-3D-Contrib

on:
  schedule:
    - cron: "0 18 * * *" # 매일 오전 3시(한국시간)
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    name: generate-github-profile-3d-contrib
    steps:
      - uses: actions/checkout@v3
      - uses: yoshi389111/github-profile-3d-contrib@0.7.1
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
          USERNAME: ${{ github.repository_owner }}
          SET_PRIVATE: true
      - name: Commit & Push
        run: |
          git config user.name shinyoung-blip
          git config user.email shinyoung@spotter.kr
          git add -A .
          git commit -m "generated"
          git push
